
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
light: !include_dir_list lights
camera: !include_dir_list cameras
switch: !include_dir_merge_list switches

api:

logger:
  default: info


octoprint:
  name: Ender5Plus
  host: 192.168.1.97
  api_key: F2A92FB9DE91467BA91789ACD01E307F
  bed: true
  number_of_tools: 1


wemo:
  discovery: true
  static: 
    - 10.0.0.179
    - 10.0.0.144
    - 10.0.0.168

# Example configuration.yaml entry
notify:
  - name: Mobile_Notifier
    platform: pushover
    api_key: a7fkfr93cnpzdf9r9ox9gt4ox8sf5z
    user_key: u55mpcbkpp45d9ipxk7s4x9ovfy1ha
