
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
light: !include_dir_list lights
camera: !include_dir_list cameras

logger:
  default: info
