- platform: rest
  name: River Water Height
  resource: https://waterservices.usgs.gov/nwis/iv/?format=json&sites=01472000&parameterCd=00065&siteStatus=all
  value_template: '{{ value_json.value.timeSeries[0]["values"][0]["value"][0]["value"] }}'
